root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
exclude_regex = [".*_test\\.go", ".*_templ\\.go"]
args_bin = []
bin = "./tmp/main"
cmd = "go build -buildvcs=false -o ./tmp/main main.go"
delay = 1000
exclude_dir = ["assets", "tmp", "vendor", "testdata", "node_modules", ".git", "generated"]
include_dir = [".", "../pkg", "../cmd"]
exclude_file = []
exclude_unchanged = true
follow_symlink = false
full_bin = ""
include_ext = ["go"]
include_file = []
kill_delay = "2s"
log = "build-errors.log"
poll = true
poll_interval = 1000
post_cmd = []
pre_cmd = []
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_root = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = false
keep_scroll = true
