services:
  # Development app container (optional)
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: templ-router-demo
    restart: unless-stopped
    ports:
      - "8084:8084"
    user: "1000:1000"
    environment:
      - GO_ENV=development
      - PORT=8090
    volumes:
      - .:/app
    command: mage dev
