# Development Dockerfile
FROM golang:1.25-alpine AS development

# Install system dependencies
RUN apk add --no-cache \
    git \
    curl \
    nodejs \
    npm

# Install development tools
RUN go install github.com/air-verse/air@latest
RUN go install github.com/a-h/templ/cmd/templ@latest
RUN go install github.com/magefile/mage@latest
RUN go install github.com/denkhaus/templ-router/cmd/template-generator@latest

# Set working directory
WORKDIR /app

# Copy go mod files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Install Node.js dependencies for Tailwind
RUN npm install -g pnpm


# Copy source code
COPY . .

RUN cd demo && pnpm install
# Generate Templ code
RUN templ generate

# Build Tailwind CSS
RUN mage build:tailwindClean

# Expose port
EXPOSE 8084

# Default command (can be overridden in docker-compose)
CMD ["mage", "dev"]
