# Docker Compose for temple-router development

services:
  temple-router-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8084:8084"
    volumes:
      - .:/app
      - go-mod-cache:/go/pkg/mod
    environment:
      - CGO_ENABLED=0
      - GOOS=linux
      - GOARCH=amd64
      - GOCACHE=/tmp/go-build
      - GOMODCACHE=/go/pkg/mod
    working_dir: /app/demo
    user: "0:0"
    command: sh -c "cd /app/demo && air -c /app/.air.toml"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  go-mod-cache:
