blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/denkhaus/templ-router/wiki
    about: Check our documentation for guides and examples
  - name: 💬 Discussions
    url: https://github.com/denkhaus/templ-router/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Issues
    url: https://github.com/denkhaus/templ-router/security/advisories/new
    about: Report security vulnerabilities privately