name: Auto Changelog

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: 1.24

    - name: Install Mage
      run: go install github.com/magefile/mage@latest

    - name: Generate changelog
      run: mage changelog:update

    - name: Commit changelog
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add CHANGELOG.md
        git diff --staged --quiet || git commit -m "chore: update changelog [skip ci]"
        git push